version: "3.9"
services:
  nginx:
    image: dasskelett/nginx-quic
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/www/:/var/www/:ro
      - ./nginx/log/:/var/log/nginx/
      - ./nginx/cert/:/etc/nginx/cert/:ro
